export const riderConstants = {
  RIDER_DATA: "RIDER_DATA",
  RIDER_CHAT_DATA: "RIDER_CHAT_DATA",
  RIDER_MESSAGES: "RIDER_MESSAGES",
  FETCH_RIDERS: "FETCH_RIDERS",
  FETCH_RIDER: "FETCH_RIDER",
  USER_TOKEN: "USER_TOKEN",
};
